application: amazon-wish-japan
version: 1
runtime: python
api_version: 1

handlers:
- url: /update_list
  script: wsgi.py
  login: admin
- url: /update_pages
  script: wsgi.py
  login: admin
- url: /config
  script: wsgi.py
  login: admin
- url: /login
  script: wsgi.py
  login: admin
- url: /callback
  script: wsgi.py
  login: admin
- url: /tweet_new_item
  script: wsgi.py
  login: admin

- url: /add_certifier
  script: wsgi.py
  login: admin
- url: /edit/.*
  script: wsgi.py
- url: /download/.*
  script: wsgi.py

- url: /static/
  static_dir: static
- url: /
  script: wsgi.py

builtins:
- datastore_admin: on
- remote_api: on
