application: amazon-wish-japan
version: 1
runtime: python
api_version: 1

handlers:
- url: /update_list
  script: wsgi.py
  login: admin
- url: /update_pages
  script: wsgi.py
  login: admin
- url: /config
  script: wsgi.py
- url: /
  script: wsgi.py

builtins:
- datastore_admin: on
